backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/home/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Visual Poetry"
        name: "gallery"
        file: "src/content/gallery/index.yaml"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }

  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
