backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/home/index.md"
        fields:
          - { label: "Author", name: "author", widget: "string", required: false }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
          - { label: "About Title", name: "aboutTitle", widget: "string", required: false }
          - { label: "About Image", name: "aboutImage", widget: "image", required: false }
          - { label: "About Text", name: "body", widget: "markdown", required: false }
          - { label: "Gallery Title", name: "galleryTitle", widget: "string", required: false }
          - { label: "Connect Image", name: "connectImage", widget: "image", required: false }
          - { label: "Connect Title", name: "connectTitle", widget: "string", required: false }
          - { label: "Connect Subtitle", name: "connectSubtitle", widget: "text", required: false }
          - { label: "Connect Handle", name: "connectHandle", widget: "string", required: false }
          - { label: "Connect Handle URL", name: "connectHandleUrl", widget: "string", required: false }
          - { label: "Connect Quote", name: "connectQuote", widget: "string", required: false }

      - label: "Visual Poetry"
        name: "gallery"
        file: "src/content/gallery/index.yaml"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }

      - label: "Quotes"
        name: "quotes"
        file: "src/content/quotes/index.yaml"
        fields:
          - label: "Quotes"
            name: "quotes"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Attribution", name: "attribution", widget: "string", required: false }

  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
